### ISSUE TITLE
Resultscript and resultsparameters are not saved in apr file.

### ISSUE THREAD

**Issue by Gundersanne** [exporl/apex#224]
Both `<resultsparameters/>` and `<resultscript/>`  which are specified in an experiment file and then applied when viewing results after the experiment, are not saved in the results file.

As a consequence when opening the results file directly the script and parameters are gone.

This will require changes in both apexwriters (for resultscript) and `RTResultSink::newResults` (parsing the  extra xml).

**Comment by linusdm** [comment]
Fixed with f88bcf52e75b0027a5984614c3eeee0cc99bdc3c
