### ISSUE TITLE
Building from scratch fails

### ISSUE THREAD

**Issue by linusdm** [exporl/apex#252]
Some hurdles need to be taken when building apex from scratch (a fresh Ubuntu installation):

- Two dependencies missing in [compiling_instructions.txt](https://github.com/exporl/apex/blob/7ab5b66977f46e037d6a77bcbc496fc725ba6859/documentation/compiling_instructions.txt#L12): `libfftw3-dev` and `libssl-dev`
- Source files in [/apex/src/lib/streamapp/_fromv3](https://github.com/exporl/apex/tree/master/src/lib/streamapp/_fromv3) missing. Subfolder `core` is missing. Fetching it from [an older version](https://github.com/exporl/apex/blob/7754799ec9908e1caf4b367ed316ef9ff6eb30a1/src/lib/streamapp/_fromv3/core) seems to work.
- Linking fails due to duplicate definitions in [/apex/src/lib/apexmain/experimentstore/manageddirectory.cpp](https://github.com/exporl/apex/blob/7ab5b66977f46e037d6a77bcbc496fc725ba6859/src/lib/apexmain/experimentstore/manageddirectory.cpp) and [/apex/src/lib/apexmain/experimentstore/manageddirectory.h](https://github.com/exporl/apex/blob/7ab5b66977f46e037d6a77bcbc496fc725ba6859/src/lib/apexmain/experimentstore/manageddirectory.h). Removing them seems to work.

**Comment by mh21** [comment]
Thanks for the bug report!
