### ISSUE TITLE
Heartrainprocedure - randomisation buttons

### ISSUE THREAD

**Issue by SaraMagits** [exporl/apex#259]
In the heartrainprocedure, buttons should be allocated randomly on each screen as to avoid learning effects of where a certain answer is on the screen.

**Comment by linusdm** [comment]
This is fixed. Although not in the heartrain-procedure. The heartrain-procedure should only concern itself with inserting trials to allow for training in between real trials. In this particular case the buttons for the screens are generated in an xml-plugin, and could be randomized there.
