### ISSUE TITLE
Resultsviewer tablet duplicates trials 

### ISSUE THREAD

**Issue by SaraMagits** [exporl/apex#276]
In several studies (LUISTER, sentences-Nottingham) the resultsviewer duplicates the results when shown on tablet. If 3 trials have been completed, the resultsviewer shows 9 trials. The results are saved correctly in the apr file. This problem does not occur in the phoneme-Nottingham study.

**Comment by wardd64** [comment]
The fix for the flowrunner zoom problem seems to cause this issue among others. I will undo that change where necessary and look for another solution.

**Comment by linusdm** [comment]
Fixed. Without reintroducing zoom problem.
https://exporl.med.kuleuven.be/gerrit/#/c/3637/
